### PR TITLE
Android update

### PR DESCRIPTION
**Pull request by m1ga**
[ti.googlesignin-android-7.3.0.zip](https://github.com/hansemannn/titanium-google-signin/files/13999136/ti.googlesignin-android-7.3.0.zip)

### CODE REVIEW

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
Any notable changes for the release notes?

**Comment by m1ga** [comment]
nothing we use, more house keeping since I've implemented in an app last week.

22.7.0
* Added a new API client, AuthorizationClient, to help you request authorization to access the Google data associated with a signed-in account on the device.
* Deprecated getPhoneNumber with no replacement.

22.6.0
* Deprecated the APIs related to the verified phone number feature.

22.5.0
* Added a new API in BeginSignInRequest that enables developers to use Jetpack libraries to get passkeys with JSON requests.

**Comment by m1ga** [comment]
Sorry but the ZIP file didn't include all files :open_mouth:  :
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libti.googlesignin.so" not found`

 I've simply recompiled it and now it is 50kb bigger:

[ti.googlesignin-android-7.3.0.zip](https://github.com/hansemannn/titanium-google-signin/files/14001373/ti.googlesignin-android-7.3.0.zip)

can you please exchange the one in the release. No code changes or anything.

**Comment by hansemannn** [comment]
Done!

**Pull request merged**
